# Default values for hsds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of HSDS nodes
replicaCount: 1

image:
  # -- HSDS image
  repository: hdfgroup/hsds
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""

# -- Image pull secrets for HSDS pod
imagePullSecrets: []

# -- Override name of this release
nameOverride: ""

# -- Override full name of this release
fullnameOverride: ""

config:
  # -- Override common configuration values for service and data node
  common:
    log_level: WARNING
  #   bucket_name: null   # set to use a default bucket, otherwise bucket param is needed for all requests
  #   aws_region: us-east-1
  #   aws_s3_gateway: null   # use endpoint for the region HSDS is running in, e.g. 'https://s3.amazonaws.com' for us-east-1
  #   aws_access_key_id: xxx  # Replace with access key for account or use aws_iam_role
  #   aws_secret_access_key: xxx   # Replace with secret key for account
  #   aws_iam_role: hsds_role  # For EC2 using IAM roles
  # -- Override configuration values for service node
  serviceNode: {}
  # -- Override configuration values for data node
  dataNode: {}

accessControl:
  # -- List of users for authentication (see `values.yaml` for format)
  users: []
    # - name: admin
    #   password: admin
  # -- List of groups for authentication (see `values.yaml` for format)
  groups: []
    # - name: admins
    #   members:
    #     - admin

resources:
  # -- Resources for the data node container
  dataNode: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  # -- Resources for the service node container
  serviceNode: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Additional annotations to add to pod
podAnnotations: {}

# -- Configure pod security context
podSecurityContext: {}
  # fsGroup: 2000

# -- Configure container security context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  # -- Type of service
  type: ClusterIP
  # -- Service port
  port: 80

ingress:
  # -- Enable ingress
  enabled: false
  # -- Annotations to add to ingress
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- Ingress host configuration
  hosts:
    - host: chart-example.local
      paths: []
  # -- Ingress TLS configuration
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Node selector for pods
nodeSelector: {}

# -- Tolerations for pods
tolerations: []

# -- Affinity for pods
affinity: {}
