{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hsds.serviceAccountName" . }}
  labels:
    {{- include "hsds.labels" . | nindent 4 }}
rules:
  - verbs:
      - list
    apiGroups:
      - ""
      - "apps"
    resources:
      - pods
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hsds.serviceAccountName" . }}
  labels:
    {{- include "hsds.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hsds.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "hsds.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
