apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "hsds.labels" . | nindent 4 }}
type: Opaque
data:
  override.sn.yml: {{ merge .Values.config.serviceNode .Values.config.common | toYaml | b64enc | quote }}
  override.dn.yml: {{ merge .Values.config.dataNode .Values.config.common | toYaml | b64enc | quote }}
