{{- if or .Values.accessControl.users .Values.accessControl.groups -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-access-control
  labels:
    {{- include "hsds.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- if .Values.accessControl.users }}
  passwd: |
    {{- range $user := .Values.accessControl.users }}
    {{ $user.name }}:{{ $user.password }}
    {{- end }}
{{- end }}
{{- if .Values.accessControl.users }}
  groups: |
    {{- range $group := .Values.accessControl.groups }}
    {{ $group.name }}: {{$group.members | join " " }}
    {{- end }}
{{- end }}
{{- end }}
